// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("funcionarios", Schema = "ht")]
public partial class Funcionarios
{
    [Key]
    [Column("codfun")]
    public int Codfun { get; set; }

    [Required]
    [Column("nome_apelido")]
    [StringLength(100)]
    public string NomeApelido { get; set; }

    [Column("data_admissao")]
    public DateTime DataAdmissao { get; set; }

    [Column("data_demissao")]
    public DateTime? DataDemissao { get; set; }

    [Column("rg")]
    [StringLength(20)]
    public string Rg { get; set; }

    [Column("nome_rh")]
    [StringLength(100)]
    public string NomeRh { get; set; }

    [Column("apelido")]
    [StringLength(20)]
    public string Apelido { get; set; }

    [Column("setor")]
    [StringLength(50)]
    public string Setor { get; set; }

    [Column("funcao")]
    [StringLength(30)]
    public string Funcao { get; set; }

    [Column("empresa")]
    [StringLength(30)]
    public string Empresa { get; set; }

    [Column("ativo")]
    [StringLength(5)]
    public string Ativo { get; set; }

    [Column("obs")]
    [StringLength(254)]
    public string Obs { get; set; }

    [Column("portaria")]
    [StringLength(5)]
    public string Portaria { get; set; }

    [Column("impresso")]
    [StringLength(5)]
    public string Impresso { get; set; }

    [Column("local_galpao")]
    [StringLength(10)]
    public string LocalGalpao { get; set; }

    [Column("data_nascimento")]
    public DateTime? DataNascimento { get; set; }

    [Column("sexo")]
    [StringLength(15)]
    public string Sexo { get; set; }

    [Column("matricula")]
    public int? Matricula { get; set; }

    [Column("cracha")]
    public short? Cracha { get; set; }

    [Column("foto")]
    public short? Foto { get; set; }

    [Column("idade")]
    public short? Idade { get; set; }

    [Column("cadastrado_por")]
    [StringLength(20)]
    public string CadastradoPor { get; set; }

    [Column("datacadastro")]
    public DateTime? Datacadastro { get; set; }

    [Column("horacadastro")]
    public TimeSpan? Horacadastro { get; set; }

    [Column("cpd")]
    [StringLength(5)]
    public string Cpd { get; set; }

    [Column("ncamiseta")]
    [StringLength(10)]
    public string Ncamiseta { get; set; }

    [Column("ncalcado")]
    public double? Ncalcado { get; set; }

    [Column("cpf")]
    [StringLength(15)]
    public string Cpf { get; set; }

    [Column("data_altera")]
    public DateTime? DataAltera { get; set; }

    [Column("alterado_por")]
    [StringLength(30)]
    public string AlteradoPor { get; set; }

    [Column("pis")]
    [StringLength(30)]
    public string Pis { get; set; }

    [Column("transferido")]
    [StringLength(5)]
    public string Transferido { get; set; }

    [Column("contratacao")]
    [StringLength(30)]
    public string Contratacao { get; set; }

    [Column("tipo_depto")]
    [StringLength(10)]
    public string TipoDepto { get; set; }

    [Column("sub_depto")]
    [StringLength(15)]
    public string SubDepto { get; set; }

    [Column("exibir_furo")]
    [StringLength(5)]
    public string ExibirFuro { get; set; }

    [Column("codigo_setor")]
    public int? CodigoSetor { get; set; }

    [Column("telefone_residencial")]
    [StringLength(20)]
    public string TelefoneResidencial { get; set; }

    [Column("telefone_celular")]
    [StringLength(20)]
    public string TelefoneCelular { get; set; }

    [Column("status_cipa")]
    [StringLength(150)]
    public string StatusCipa { get; set; }

    [Column("data_cipa")]
    public DateTime? DataCipa { get; set; }

    [Column("ocultar_dados")]
    [StringLength(5)]
    public string OcultarDados { get; set; }

    [Column("prazo_contrato")]
    public int? PrazoContrato { get; set; }

    [Column("prazo_renova_contrato")]
    public int? PrazoRenovaContrato { get; set; }

    [Column("contrato_fixo_temp")]
    [StringLength(50)]
    public string ContratoFixoTemp { get; set; }

    [Column("codigo_anterior")]
    public int? CodigoAnterior { get; set; }

    [Column("agencia")]
    [StringLength(150)]
    public string Agencia { get; set; }

    [Column("sub_setor")]
    [StringLength(100)]
    public string SubSetor { get; set; }

    [Column("cidade")]
    [StringLength(20)]
    public string Cidade { get; set; }

    [Column("local")]
    [StringLength(20)]
    public string Local { get; set; }

    [Column("qrcode")]
    [StringLength(50)]
    public string Qrcode { get; set; }
}