// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

/// <summary>
/// Funcionarios de atendimento do Almoxarifado.
/// </summary>
[Table("tbl_atendentes_almox", Schema = "almoxarifado_jac")]
public partial class TblAtendentesAlmox
{
    [Key]
    [Column("nome_funcionario")]
    [StringLength(100)]
    public string NomeFuncionario { get; set; }

    [Column("funcao")]
    [StringLength(30)]
    public string Funcao { get; set; }

    [Column("username")]
    [StringLength(30)]
    public string Username { get; set; }
}