// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("tbl_barcodes", Schema = "producao")]
[Index("Barcode", Name = "tbl_barcodes_barcode_key", IsUnique = true)]
public partial class TblBarcodes
{
    [Required]
    [Column("barcode")]
    [StringLength(15)]
    public string Barcode { get; set; }

    [Key]
    [Column("codigo")]
    public int Codigo { get; set; }

    [Column("impresso")]
    [StringLength(5)]
    public string Impresso { get; set; }

    [Column("compra")]
    [StringLength(5)]
    public string Compra { get; set; }

    [InverseProperty("BarcodeNavigation")]
    public virtual TConfCargaGeral TConfCargaGeral { get; set; }

    [InverseProperty("BarcodeNavigation")]
    public virtual TPreConferencia TPreConferencia { get; set; }
}