// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("tbltranportadoras", Schema = "operacional")]
[Index("Nometransportadora", Name = "tbltranportadoras_nometransportadora_key", IsUnique = true)]
public partial class Tbltranportadoras
{
    [Key]
    [Column("codtransportadora")]
    public int Codtransportadora { get; set; }

    [Required]
    [Column("nometransportadora")]
    [StringLength(200)]
    public string Nometransportadora { get; set; }

    [Required]
    [Column("endereco")]
    [StringLength(200)]
    public string Endereco { get; set; }

    [Required]
    [Column("bairro")]
    [StringLength(100)]
    public string Bairro { get; set; }

    [Required]
    [Column("cep")]
    [StringLength(10)]
    public string Cep { get; set; }

    [Required]
    [Column("cidade")]
    [StringLength(150)]
    public string Cidade { get; set; }

    [Required]
    [Column("uf")]
    [StringLength(15)]
    public string Uf { get; set; }

    [Required]
    [Column("ie")]
    [StringLength(15)]
    public string Ie { get; set; }

    [Column("ccm")]
    [StringLength(15)]
    public string Ccm { get; set; }

    [Required]
    [Column("cnpj")]
    [StringLength(60)]
    public string Cnpj { get; set; }

    [Column("ddd")]
    public int Ddd { get; set; }

    [Column("fone_1")]
    public int Fone1 { get; set; }

    [Column("fone_2")]
    public int? Fone2 { get; set; }

    [Required]
    [Column("contato")]
    [StringLength(50)]
    public string Contato { get; set; }

    [Column("id_nextel")]
    [StringLength(15)]
    public string IdNextel { get; set; }

    [InverseProperty("CodtransportadoraNavigation")]
    public virtual ICollection<TRomaneio> TRomaneio { get; set; } = new List<TRomaneio>();
}