// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cipolatti.API.Models;

[Table("t_saida_almox", Schema = "almoxarifado_jac")]
public partial class TSaidaAlmox
{
    [Column("cod_movimentacao")]
    public int? CodMovimentacao { get; set; }

    [Key]
    [Column("cod_saida_almox")]
    public int CodSaidaAlmox { get; set; }

    [Column("barcode")]
    [StringLength(16)]
    public string Barcode { get; set; }

    [Column("qtde")]
    public float? Qtde { get; set; }

    [Column("data")]
    public DateTime? Data { get; set; }

    [Column("hora", TypeName = "time with time zone")]
    public DateTimeOffset? Hora { get; set; }

    [Column("resp")]
    [StringLength(50)]
    public string Resp { get; set; }

    [Column("requisicao")]
    public int? Requisicao { get; set; }

    [Column("destino")]
    [StringLength(50)]
    public string Destino { get; set; }

    [Column("incluido_por")]
    [StringLength(50)]
    public string IncluidoPor { get; set; }

    [Column("data_inclusao")]
    public DateTime? DataInclusao { get; set; }

    [Column("funcionario")]
    [StringLength(50)]
    public string Funcionario { get; set; }

    [Column("setor")]
    [StringLength(50)]
    public string Setor { get; set; }

    [Column("unidade")]
    [StringLength(10)]
    public string Unidade { get; set; }

    [Column("expurgo")]
    [StringLength(5)]
    public string Expurgo { get; set; }

    [Column("obs")]
    [StringLength(50)]
    public string Obs { get; set; }

    [Column("num_os")]
    public int? NumOs { get; set; }

    [Column("endereco")]
    [StringLength(12)]
    public string Endereco { get; set; }

    [Column("codcompladicional")]
    public int? Codcompladicional { get; set; }

    [Column("codfun")]
    public int? Codfun { get; set; }
}